import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([[1, 2], [3, 4]])

print(np.zeros((2, 3)))
print(np.ones((3, 2)))
print(np.eye(3))
print(np.full((2, 2), 7))
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))
print(np.random.rand(2, 2))
print(np.random.randn(3, 3))
print(np.random.randint(1, 10, size=(2, 3)))
print(np.random.seed(42))

print(a.shape)
print(b.ndim)
print(a.size)
print(a.dtype)
print(a.itemsize)

print(np.reshape(a, (5, 1)))
print(np.ravel(b))
print(np.transpose(b))
print(np.expand_dims(a, axis=0))
print(np.squeeze(np.array([[1], [2], [3]])))

print(np.append(a, 6))
print(np.insert(a, 2, 99))
print(np.delete(a, 1))

print(np.concatenate((a, a)))
print(np.stack((a, a)))
print(np.hstack((a, a)))
print(np.vstack((a, a)))
print(np.split(a, 5))
print(np.array_split(a, 3))

print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))
print(np.min(a))
print(np.max(a))
print(np.percentile(a, 50))
print(np.sum(a))
print(np.prod(a))
print(np.cumsum(a))
print(np.cumprod(a))
print(np.diff(a))
print(np.sort(a))

print(np.where(a > 3))
print(np.nonzero(a))
print(np.unique(a))
print(np.isin(a, [2, 10]))
print(np.any(a > 3))
print(np.all(a > 0))

print(np.equal(a, a))
print(np.greater(a, 2))
print(np.less_equal(a, 5))

print(np.dot(a[:3], a[:3]))
print(np.matmul(b, b))
print(np.linalg.inv(np.array([[1., 2.], [3., 4.]])))
print(np.linalg.det(np.array([[1., 2.], [3., 4.]])))
print(np.linalg.eig(np.array([[1., 2.], [2., 1.]])))
